global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: grafana
    static_configs:
      - targets: ['grafana:3000']
  - job_name: wakatime-exporter
    static_configs:
      - targets: ['wakatime-exporter:9212']
